import * as THREE from 'three'
import { stdMaterial } from '../../../../lib/blocks'

/** 中央车站材质谱：维多利亚铁路砖石 + 锻铁钢构 + 铜绿尖顶 + 鎏金钟表�? *  全部参数化材质（纯色/金属�?粗糙�?自发光），无贴图无外部资源�?*/
export const C = {
  brick: '#8E5A46',
  brickDark: '#774634',
  brickLight: '#A2705A',
  stone: '#D8D3C7',
  stoneDark: '#B7B0A1',
  stoneWarm: '#CFC3A8',
  iron: '#3A4046',
  ironDark: '#2A2E33',
  cast: '#4E555A',
  steel: '#8D8880',
  patina: '#4C7C6C',
  patinaLight: '#5F9280',
  gold: '#C9A227',
  goldPale: '#E0CE8C',
  glass: '#7C9BB2',
  glassDeep: '#2E4057',
  ballast: '#6E6961',
  rail: '#9A9488',
  sleeper: '#57402E',
  wood: '#7A5A3C',
  woodDark: '#4E3A28',
  locoGreen: '#1E4636',
  locoBlack: '#22252A',
  carriageRed: '#792E2A',
  carriageCream: '#E6DDC6',
  paving: '#BAB4A7',
  pavingDark: '#8E887C',
  asphalt: '#6C6F73',
  grass: '#87A45F',
  grassDark: '#6F8C4C',
  hedge: '#5C7A46',
  white: '#F2EFE6',
  glow: '#FFE9A8',
  signalRed: '#A8332C',
  chalk: '#DCE3E8',
  sand: '#C8B48A',
} as const

export const MATS: Record<string, THREE.Material> = {
  brick: stdMaterial(C.brick, { roughness: 0.9 }),
  brickDark: stdMaterial(C.brickDark, { roughness: 0.92 }),
  brickLight: stdMaterial(C.brickLight, { roughness: 0.88 }),
  stone: stdMaterial(C.stone, { roughness: 0.82 }),
  stoneDark: stdMaterial(C.stoneDark, { roughness: 0.86 }),
  stoneWarm: stdMaterial(C.stoneWarm, { roughness: 0.8 }),
  iron: stdMaterial(C.iron, { metalness: 0.62, roughness: 0.44 }),
  ironDark: stdMaterial(C.ironDark, { metalness: 0.6, roughness: 0.5 }),
  cast: stdMaterial(C.cast, { metalness: 0.5, roughness: 0.55 }),
  steel: stdMaterial(C.steel, { metalness: 0.85, roughness: 0.32 }),
  patina: stdMaterial(C.patina, { metalness: 0.38, roughness: 0.62 }),
  patinaLight: stdMaterial(C.patinaLight, { metalness: 0.34, roughness: 0.66 }),
  gold: stdMaterial(C.gold, { metalness: 0.8, roughness: 0.28, emissive: '#4A3A0C', emissiveIntensity: 0.25 }),
  goldPale: stdMaterial(C.goldPale, { metalness: 0.6, roughness: 0.35 }),
  glass: stdMaterial(C.glass, { metalness: 0.45, roughness: 0.16, emissive: '#22323E', emissiveIntensity: 0.35 }),
  glassDeep: stdMaterial(C.glassDeep, { metalness: 0.6, roughness: 0.22, emissive: '#1B2A3A', emissiveIntensity: 0.4 }),
  ballast: stdMaterial(C.ballast, { roughness: 0.98 }),
  rail: stdMaterial(C.rail, { metalness: 0.9, roughness: 0.28 }),
  sleeper: stdMaterial(C.sleeper, { roughness: 0.92 }),
  wood: stdMaterial(C.wood, { roughness: 0.85 }),
  woodDark: stdMaterial(C.woodDark, { roughness: 0.88 }),
  locoGreen: stdMaterial(C.locoGreen, { metalness: 0.3, roughness: 0.42 }),
  locoBlack: stdMaterial(C.locoBlack, { metalness: 0.45, roughness: 0.5 }),
  carriageRed: stdMaterial(C.carriageRed, { metalness: 0.22, roughness: 0.45 }),
  carriageCream: stdMaterial(C.carriageCream, { roughness: 0.6 }),
  paving: stdMaterial(C.paving, { roughness: 0.9 }),
  pavingDark: stdMaterial(C.pavingDark, { roughness: 0.92 }),
  asphalt: stdMaterial(C.asphalt, { roughness: 0.95 }),
  grass: stdMaterial(C.grass, { roughness: 0.96, emissive: '#42672F', emissiveIntensity: 0.32 }),
  grassDark: stdMaterial(C.grassDark, { roughness: 0.96, emissive: '#33521F', emissiveIntensity: 0.3 }),
  hedge: stdMaterial(C.hedge, { roughness: 0.97 }),
  white: stdMaterial(C.white, { roughness: 0.5 }),
  glow: stdMaterial(C.glow, { emissive: C.glow, emissiveIntensity: 1.5, roughness: 0.4 }),
  signalRed: stdMaterial(C.signalRed, { metalness: 0.2, roughness: 0.5 }),
  chalk: stdMaterial(C.chalk, { metalness: 0.5, roughness: 0.2, emissive: '#2A3B4A', emissiveIntensity: 0.3 }),
  sand: stdMaterial(C.sand, { roughness: 0.98 }),
}

export function mat(key: string): THREE.Material {
  const m = MATS[key]
  if (!m) throw new Error(`未登记的材质键：${key}`)
  return m
}
